version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: yarn run start:dev
    volumes:
      - .:/app
    # env_file: .env
    ports:
      - 8080:3000

volumes:
  daming-volume:
    external: true

networks:
  daming-network:
    external: true
