# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Express Postgres Ts Starter Build Workflow

on:
 push:
  branches: [master, develop, workflows-fix]
 pull_request:
  branches: [master, develop]

jobs:
 lint:
  name: build express postgres ts starter
  runs-on: ${{ matrix.os }}

  strategy:
   matrix:
    node-version: [12.x, 14.x]
    os: [windows-last, macos-last, ubuntu-latest]

  steps:
   - name: Check out git repository
     uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
      node-version: ${{ matrix.node-version }}

   - name: Install yarn
     run: npm install -g yarn

   - name: Install 3rd library
     run: yarn

   - name: build starter
     run: npm install -g yarn && yarn && yarn build

   - name: cleanup artifacts
     run: npx rimraf "dist"
