# Copyright 2020 大明二代
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Express Postgres Ts Starter CI Workflow

on:
 push:
  branches: [master, develop]
 pull_request:
  branches: [master, develop]

env:
 REGISTRY_NAME: github.com

jobs:
 build:
  runs-on: ${{ matrix.os }}

  strategy:
   matrix:
    node-version: [20.x]
    os: [windows-latest, macos-latest, ubuntu-latest]

  steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
      node-version: ${{ matrix.node-version }}
   - name: Get yarn cache directory path
     id: yarn-cache-dir-path
     run: echo "::set-output name=dir::$(yarn cache dir)"

   - uses: actions/cache@v2
     id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
     with:
      path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
       ${{ runner.os }}-yarn-
   - name: Install yarn
     run: npm install -g yarn
   - name: Install 3rd library
     run: yarn
   - name: Lint check
     if: matrix.os == 'ubuntu-latest'
     run: yarn lint
   - name: Build check
     run: yarn build
   - name: Test check
     if: matrix.os == 'ubuntu-latest'
     run: yarn test:ci
 build-muilt-node-version:
  runs-on: ${{ matrix.os }}
  needs: [build]
  strategy:
   matrix:
    node-version: [16.x, 18.x, 20.x]
    os: [ubuntu-latest]

  steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
      node-version: ${{ matrix.node-version }}
   - name: Get yarn cache directory path
     id: yarn-cache-dir-path
     run: echo "::set-output name=dir::$(yarn cache dir)"

   - uses: actions/cache@v2
     id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
     with:
      path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
       ${{ runner.os }}-yarn-
   - name: Install yarn
     run: npm install -g yarn
   - name: Install 3rd library
     run: yarn
   - name: Lint check
     run: yarn lint
   - name: Build check
     run: yarn build
   - name: Test check
     run: yarn test:ci
 build-docker:
  runs-on: ubuntu-latest
  needs: [build, build-muilt-node-version]
  steps:
   - uses: actions/checkout@master
   # Container build
   - name: Build docker
     id: build-docker
     run: |
      docker build . -t ${{ env.REGISTRY_NAME }}/damingerdai/express-postgres-ts-starter:${{ github.sha }} -f Dockerfile
   - name: Image digest
     run: echo ${{ steps.build-docker.outputs.digest }}
