# main.yml

# Workflow's name
name: Build Express App

# Workflow's trigger
on:
 push:
  branches: [master, develop, workflows-fix]

# Workflow's jobs
jobs:
 # job's id
 release:
  # job's name
  name: build express postgres ts starter

  # the type of machine to run the job on
  runs-on: ${{ matrix.os }}

  # create a build matrix for jobs
  strategy:
   matrix:
    os: [windows-last, macos-last, ubuntu-latest]

  # create steps
  steps:
   - name: Check out git repository
     uses: actions/checkout@v2

   - name: Install Node.js
     uses: actions/setup-node@v2-beta

   - name: Install yarn
     run: |
      npm install -g yarn

   - name: Install 3rd library
     run: |
      yarn

   - name: build express app
     run: |
      yarn build

   - name: cleanup artifacts
     run: |
      npx rimraf "dist"
