# main.yml

# Workflow's name
name: Build Express App

# Workflow's trigger
on:
 push:
  branches: [master, develop, workflows-fix]

# Workflow's jobs
jobs:
 # job's id
 release:
  # job's name
  name: build and release electron app

  # the type of machine to run the job on
  runs-on: ${{ matrix.os }}

  # create a build matrix for jobs
  strategy:
   matrix:
    os: [windows-2019, macos-10.15]

  # create steps
  steps:
   - name: Check out git repository
     uses: actions/checkout@v2

   - name: Install Node.js
     uses: actions/setup-node@v2

   - name: Install yarn
     run: |
      npm install -g yarn

   - name: Install 3rd library
     run: |
      yarn

   - name: build express app
     if: matrix.os == 'windows-2019'
     run: |
      yarn build

   - name: build express app
     if: matrix.os == 'macos-10.15'
     run: |
      yarn build

   # step5: cleanup artifacts in dist_electron
   - name: cleanup artifacts
     run: |
      npx rimraf "dist"
